### ISSUE TITLE
非常感谢您的demo,但是模拟器上运行报错了，请问该咋弄啊

### ISSUE THREAD

**Issue by wywzixin** [1uokun/react-native-mapbox-demo#1]
![image](https://user-images.githubusercontent.com/22430715/45634904-303ef480-bad6-11e8-9792-02bff31d7632.png)

**Comment by 1uokun** [comment]
[https://github.com/1uokun/react-native-mapbox-demo/commit/671213d0a818b2951aa41443e4c9a5d26585fd7d](https://github.com/1uokun/react-native-mapbox-demo/commit/671213d0a818b2951aa41443e4c9a5d26585fd7d)按照这个commit删除`react-native-mytoast`。非常抱歉上传代码后没有review代码，给您带来的困惑深感抱歉

**Comment by wywzixin** [comment]
嗯嗯，运行成功了，谢谢您的demo, 国内找点儿react native+ mapbox的资料真不好找，幸好有您的例子，感谢，祝您中秋节快乐
